package org.platform.vehicle.response;

/**
 * 接口响应码
 */
public class ResponseCode {

    /*---------------------------------------------------请保持工整----------------------------------------------------**/
    public static final String SUCCESS = "000000";// 表示成功
    public static final String UNKNOW_EXCEPTION = "999999"; // 未知异常
    public static final String ERROR = "999999";// 表示失败

    public static final String USER_DISABLE_ER = "010001"; // 用户已被禁用
    public static final String NOT_EXIST_USER = "010003"; // 不存在的用户
    public static final String USER_NOT_ADMIN = "010002"; // 不存在的用户
    public static final String OUT_TIME_TOKEN = "010004";// token 失效---&&勿动(前端有判断)
    public static final String NOT_LOGIN = "010005"; // 用户未登录---&&勿动(前端有判断)
    public static final String NOT_EXIST_TOKEN = "010006";// token 不存在---&&勿动(前端有判断)
    public static final String REQ_PARAM_NOT_EXIST = "010007";// 请求参数不存在
    public static final String TYPE_INIT_DATA_ERROR = "010008";// 初始化数据不支持修改或删除
    public static final String MERCHANT_LOGINSTATE_ERROR = "010009";
    public static final String SELECT_DATA_ISNULL = "010010"; //查询结果为空！
    public static final String DATA_ERROR = "010011";//数据交互错误
    public static final String NOT_CACHED_USER = "010012"; //用户未在线，请重新登录
    public static final String NOT_EXIST_ROLE = "010013"; //没有相关权限

    public static final String REQUEST_PARAM_ERROR = "010023";  //请求参数格式错误
    public static final String USER_CODE_REPEAT_ERROR = "010024"; //用户账号重复！
    public static final String NOT_SUPPORT_DEVICE_TYPE = "010025";// 不支持，该设备实现
    public static final String USER_MOBILE_REPEAT_ERROR = "010026"; //手机号码重复！
    public static final String USER_NAME_ERROR = "010027";
    public static final String USER_UPDATEADMIN_ERROR = "010028";
    public static final String USER_FAILURE_DELETE = "010029";
    public static final String FINALE_DATA_ISNULL = "010030";
    public static final String ROLE_NOT_EXIST = "010031";
    public static final String ROLE_NAME_REPEAT_ERROR = "010032";
    public static final String SYSUSER_ROLE_ERROR = "010033";
    public static final String ROLE_MENU_ONE_ERROR = "010034";
    public static final String SALE_TYPE_ERROR = "010035";
    public static final String SALEMAN_NUM_ERROR = "010036";
    public static final String SALES_NAME_ERROR = "010037";
    public static final String SALES_YTNUM_ERROR = "010038";
    public static final String FILEUPLOAD_ERROR = "010039";//上传文件异常
    public static final String PHONE_BIND_ERROR = "010041"; //手机号码已被绑定
    public static final String PHONE_BIND_BIND_ERROR = "010042";//该用户已绑定过手机号码
    public static final String DATE_FORMAT_ERROR = "010043";//时间格式有误
    public static final String DATA_NULL_ERROR = "010044";//空指针异常
    public static final String FEIGN_ERROR = "010045";//Feign调用异常

    /*---------------------------------------------------请保持工整----------------------------------------------------**/
    public static final String VERFIY_NOT_TOKEN = "100000";// token 不存在
    public static final String CODE_NOT_TOKEN = "100001";//图形验证码不存在
    public static final String USER_NOT_EXIST = "100002";//用户信息不存在
    public static final String PASSWORD_ERROR = "100009";//密码输入错误
    public static final String PASSWORD_ERROR_LENGTH = "100011";//密码长度只能在6-16位
    public static final String PASSWORD_ERROR_FORMAT = "100012";//密码输入格式不正确
    public static final String PASSWORD_ERROR_CONFIRM = "100013";//新密码与确认密码不一致
    public static final String OLD_PASSWORD_ERROR = "100014";//原密码输入错误
    public static final String USER_CODE_ERROR = "100015";//用户工号格式输入不正确

    /*---------------------------------------------------请保持工整----------------------------------------------------**/
    public static final String IMAGE_ERROR_BASE64STR = "200000";//图形验证码转换失败
    public static final String USER_ROLE_NOT_EXIST = "200001"; //用户所属角色未分配
    /*---------------------------------------------------请保持工整----------------------------------------------------**/
    public static final String TASK_RUNUPTIME_ERROR = "300001";  //任务开始时间小于当前系统时间
    public static final String TASK_ENDTIME_ERROR = "300002";  //任务结束时间小于任务启动时间
    public static final String TASK_TYPE_NOT = "300003";   //任务类型不存在
    public static final String TASK_SONTYPE_NOT = "300004";//子任务类型不存在
    public static final String TASK_SILEDE_NAME_REPEAT = "300005";//轮播图名称重复
    public static final String TASK_SILEDE_LEV_REPEAT = "300006";//轮播图顺序重复
    //    public static final String TASK_GETNUM_ERROR="300008";//添加任务时任务可多选时参数不正确
    public static final String TASK_NAME_REPEAT = "300009";//轮播图名称重复
    public static final String TASK_SLIDESHOW_LEV_ERROR = "300010";//轮播图顺序错误
    public static final String TASK_REGION_ERROR = "300011";
    public static final String TASK_MONEY_ERROR = "300012";//任务预算金额大于商家当前余额
    public static final String TASK_BYPLAN_ERROR = "300013"; //任务进度状态错误，请联系管理员查看
    public static final String TASK_MERCHANTINFO_ERROR = "300014"; //商家信息不存在，请去完善商家信息或更改商家名称再次查询
    public static final String TASK_MOENY_IMPREST = "300015"; //任务实际金额与预计金额不符
    public static final String DATE_NULL_ERROR = "300016"; //暂无数据
    public static final String TASK_MERCHANT_ERROR = "300017"; //暂无数据
    public static final String SALES_MISSION_ERROR = "300018"; //该任务正在进行中
    public static final String PAGE_UPLOAD_ERROR = "300019"; //图片数据为空
    public static final String TASK_MOENY_MORE_IMPREST = "300020";//预支付金额超过商家余额
    public static final String LONGITUDE_LATITUDE_ERROR = "300021";//获取经纬度失败
    public static final String PROVINCE_DATE_NULL = "300022";//省数据不存在
    public static final String LONGITUDE_LATITUDE_DATE = "300024";//经纬度添加失败
    public static final String LESS_MONEY = "300025";//赏金余额不足1元,无法提现
    public static final String TASK_IS_DRAFT = "300026";//当前任务为草稿
    public static final String PHOTO_DOWNLOAD_ERROR = "300027";//当前任务为草稿
    public static final String PHOTO_URL_ERROR = "300028";//当前任务为草稿
    public static final String GET_REGION_ERROR = "300029";//获取地理位置错误
    public static final String BAIDU_API_SERVER_ERROR = "300030";//服务器内部错误
    public static final String BAIDU_API_PARAM_ERROR = "300031";//传入参数错误，若操作无误，请联系管理员
    public static final String BAIDU_API_LIMIT_ERROR = "300032";//今日获取经纬度上限
    public static final String LESS_ONE_MONEY = "300033";//赏金余额不足,无法提现
    public static final String CHECK_ON_AGREEMENT = "300034";//请勾选协议继续注册
    public static final String SIGN_RE_DATE = "300035";//当前签到模式存在
    public static final String DATA_IS_NULL = "300036";//当前签到模式存在
    public static final String DATA_ERROR_SIGNBYADD = "300037";//当前签到模式存在
    public static final String DATA_REPEAT_SIGN = "300038";//当前签到模式存在
    public static final String TODAY_SIGN_RE = "300039";//当前签到模式存在
    public static final String SIGN_ERROR_TODAY = "300040";//当前签到模式存在
    public static final String LUCKY_CHANCE_ERROR = "300041";//奖品概率设置总和不能超过100
    public static final String PERSON_PERMISSION_ERROR = "300042";//该用户没有抽奖权限
    public static final String PERSON_DAYTIMES_ERROR = "300043";//用户当日抽奖次数用尽
    public static final String PERSON_TOTAL_TIMES_ERROR = "300044";//用户总抽奖次数用尽
    public static final String PERSON_INTEGRAL_LESS_ERROR = "300045";//用户积分不足
    public static final String PRIZE_COUNT_ERROR = "300046";//奖品数目出错
    public static final String PRIZE_TIME_OVER = "300047";//抽奖活动已经结束
    public static final String PRIZE_TIME_NO_BEGIN = "300048";//抽奖活动还未开始
    public static final String PRIZE_ADDRESS_REPEAT = "300049";//兑奖信息已经填写过
    public static final String TASK_PLATFORM_ERROR = "300051";//分享平台数据错误
    public static final String TASK_COMMENT_ERROR = "300052";//分享平台数据错误
    public static final String DATE_ERROR_EXCEPTION = "300053";//兑奖信息已经填写过
    public static final String SIGN_ERROR_NOTHAVE = "300054";//兑奖信息已经填写过
    public static final String SIGN_INTEGRAL_MAX = "300055";//兑奖信息已经填写过
    public static final String PROFIT_ERROR = "300056";//分润信息错误
    public static final String TASK_AUDIT_PHONENAME = "300057";//当前任务需要提交姓名和电话
    public static final String TASK_ERROR_TAGS = "300058";//抽奖活动还未开始
    public static final String GAME_TIMES_ERROR = "300059";//游戏关卡抽奖次数为0
    public static final String ACTIVE_NOT_FOUND = "300060";//未查询到此类抽奖活动---&&勿动(前端有判断)
    //public static final String ACTIVE_ONLY_ONE="300061";//首页抽奖活动仅能添加一条
    public static final String PRIZE_TYPE_UN_COUNT = "300062";//必须添加一个未中奖奖项
    public static final String TASK_MONEYALL_ERROR = "300063";//赏金错误
    public static final String LIMIT_ERROR_EXCEPTION = "300064";//兑奖信息已经填写过

    public static final String RULE_DATE_OUT_ERROR = "300065";//设置积分过期时间不能超前
    public static final String RULE_TOO_SMALL_ERROR = "300066";//积分上限设置必须大于任务或闯关积分设置
    public static final String RULE_SCORE_UPPER_ERROR = "300067";//您的积分已达上限!
    public static final String RULE_RULE_ERROR = "300068";//积分系统未开启!
    public static final String LUCKY_BAD_BAD = "300069";//谢谢参与---&&勿动(前端有判断)
    public static final String LUCKY_BAD_PRIZE = "300070";//请至少配置一个未中奖奖品!

    /*------------------------------------------------------请保持工整-------------------------------------------------**/
    public static final String QR_CODE_ERROR = "4000001";//二维码相关错误
    public static final String PAY_TYPE_ERROR = "4000001";//错误的支付方式
    public static final String RULES_INTEGRAL_ERROR = "4000002";//该条积分规则不存在
    public static final String PAY_ZFB_ERROR = "400003";//支付宝支付异常
    public static final String MATERIAL_ERROR = "4000102";//素材相关数据设置错误
    public static final String MATERIAL_OPEN_ERROR = "4000103";//素材相关数据设置错误
    public static final String FX_MAX_RATE_ERROR = "4000104";//分销比率最大设置不能超过50%
    public static final String FX_SALE_REPEAT = "4000105";//已是分销员。无法再次申请
    public static final String NOT_SALE_FX = "4000106";//已是分销员。无法再次申请
    public static final String FX_MODEL_ERROR = "4000107";//分销模式设置错误(或分销暂未开启)
    public static final String ORDER_STATUS_ERROR = "4000108";//订单状态错误
    public static final String SALE_MONEY_FREEZE = "4000109";//账户已被冻结。请联系客服
    public static final String VIP_SET_ERROR = "4000110";//会员相关设置错误
    public static final String VIP_SALECOUNT_GTZERO = "4000111";//当前会员等级人数大于0(不可删除,请前往分销员列表对会员等级手动操作
    public static final String FX_AWARDMODEL_ERROR = "4000112";//新增分销数据与设置不通，请刷新当前页面操作
    public static final String FX_NO_SETTLEMENT = "4000113";//业务员存在未结算订单,暂不可停止分销
    public static final String BEFORE_VIPDATA_ERROR = "4000114";//上级会员数据相关错误(请联系管理员查看详情或重试)
    public static final String VIP_GTDATA_ERROR = "4000115";//当前等级数据应该大于上级数据
    public static final String NOWLEVEL_VIPSET_ERROR = "4000116";//当前等级VIP相关数据设置错误
    public static final String GOODINFO_REPLACE = "4000117";//商品信息发生变化。请刷新重试或联系客服
    public static final String COMPLETE_PAGE_PARAM = "4000118";//时间周期请完善
    public static final String SALE_OR_GOODS_ERROR = "4000119";//未获取到用户或者商品信息
    public static final String ES_INSERT_DATA_ERROR = "4000120";//新增ES数据错误!
    public static final String ORDER_GOODS_DIS_ERROR = "4000121";//订单未结算不支持评论
    public static final String ORDER_DIS_DIS_ERROR = "4000122";//订单不支持重复评论!
    public static final String HAVING_ORDER_COMMENT = "4000123";//含有已评论订单!!
    public static final String DIS_NOT_EXIST_ERROR = "4000124";//查询消息内容出错!
    public static final String OPERATION_OFTEN_ERROR = "4000125";//操作过于频繁
    public static final String USER_CODE_APPLYING = "4000126";//商家审核中...
    public static final String PERSON_BARNCH_ERROR = "4000127";//个人店铺未设置是否未快递网点
    public static final String LICENSEURL_ERROR = "4000128";//营业执照图片不能为空
    public static final String SAFETYPERMISSIONURL_ERROR = "4000129";//食品安全许可证不能为空
    public static final String FIRMNAME_ERROR = "4000130";//企业名称不能为空
    public static final String TIME_OUT = "4000131";//超时
    public static final String MERCNAME_REPLAY = "4000132";//店铺名称重复
    public static final String MERCPHONE_REPLAY = "4000133";//手机号重复
    public static final String SAVE_IMAGE_ERROR = "4000134";//当前分享类型下图片错误
    public static final String NOT_STOREGOOD_OWNER = "4000135";// 你不是当前商品店主
    public static final String BILL_CONFIRMED_ERROR = "4000136";
    public static final String REFUSE_ILLEGAL_OPERATION = "4000137";
    public static final String BILL_CONNOT_CONFIRM = "400138";
    public static final String BILL_CONNOT_CONFIRM_NOTPAY = "400139";
    public static final String BILL_CONFIRM_PAY_ERROR = "400140";
    public static final String PRODUCT_SIZE_ERROR = "400141";//商品数量错误

    /*--------------------------------------------------请保持工整-----------------------------------------------------**/
    public static final String ORDER_NOT_PAY = "500001";                // 订单未支付
    public static final String UNKNOWN_PAYMENT = "500002";              // 未知的支付方式
    public static final String LIMIT_APPLY = "500003"; // 超出申请次数
    public static final String OUT_OF_AFTER_SALE_TIME = "500004"; //超出售后时限
    public static final String RETURN_STATUS_ERROR = "500005"; //退货状态异常，无法操作
    public static final String ORDER_CAN_NOT_REFUND_STATUS = "500006"; //订单状态不支持售后
    public static final String STORE_TYPE_ERROR = "500007"; //该订单不属于此商城，无法查看
    public static final String RETURN_GOODS_STATUS_ERROR = "500008"; //商品还未收到，无法进行退款
    public static final String AFTER_SALE_APPLY_REPEAT = "500009"; //此订单正在售后中，无法重复申请
    public static final String CAN_NOT_REFUND_DFK_STATUS = "500010"; //订单待付款不支持售后
    public static final String CAN_NOT_REFUND_YGB_STATUS = "500011"; //订单已关闭不支持售后
    public static final String CAN_NOT_REFUND_YJS_STATUS = "500012"; //订单已结算不支持售后
    public static final String CAN_NOT_AFTER_SALE_ORDER = "500013"; //此订单不支持售后服务
    public static final String MERCHAN_TYPE_NAME_ERROR = "500014";//商家类型名称重复
    public static final String SALE_TYPE_NAME_ERROR = "500015";//业务员类型名称重复
    public static final String SALETYPE_NUM_ERROR = "500016";//该业务员类型不存在
    public static final String MISSION_TYPE_NAME_ERROR = "500017";//任务类型名称重复
    public static final String AUDIT_TYPE_NAME_ERROR = "500018";//审核类型名称重复
    public static final String MISSION_NUM_ERROR = "500020";//业务员申请的任务不足
    public static final String NEWS_TYPE_ERROR = "500021";//消息无响应对象
    public static final String MISSION_EMPTY_ERROR = "500022";//任务不存在
    public static final String MISSION_ENOUGH_ERROR = "500023";//二级目录无法继续添加
    public static final String SALEMAN_EMPTY_ERROR = "500024";//业务员不存在---&&勿动(前端有判断)
    public static final String NEWS_CODE_ERROR = "500025";//消息标题格式错误
    public static final String MISSION_TYPE_NAME_FORMAT_ERROR = "500026";//任务类型名称格式不正确
    public static final String LNG_LAT_NULL = "500028";//距离最近时请输入经纬度
    public static final String MERCHANT_NULL_ERROR = "500029";//该商家获取失败[账号可能被停用或删除]
    public static final String MERCHANT_MONEY_ERROR = "500030";//加款不允许超过 100000 RMB
    public static final String SALES_MISSIONTIME_ERROR = "500031";//业务员任务不在进行中
    public static final String AUDIT_TASK_ISNULL = "500032"; //业务员任务不存在
    public static final String SELECT_TIME_ERROR = "500033";//该业务员的任务状态不明
    public static final String CAN_NOT_REMIND_MORE = "500034"; //已超出催单限制次数，请电话联系客服询问
    public static final String CAN_NOT_REMIND_STATUS = "500035"; //订单状态不支持催单
    public static final String DURING_PEOMISE_DELIVERY_TIME = "500036"; //订单处于正常发货时效中，商家会尽快安排发货
    public static final String REMIND_LATER = "500037"; //商家已经收到催单信息，请于催单24小时后再次尝试
    public static final String NO_ORDER_TO_REMIND = "500038"; //当前没有需要催单的订单
    public static final String MISSION_LIMIT_ERROR = "500039";//业务员申请的任务不足
    public static final String MISSION_ADDR_ERROR = "500040";//业务员申请的任务不足
    public static final String PAY_PARAM_ERROR = "500041";//支付参数错误
    public static final String PAY_ERROR = "500042";//支付异常
    public static final String RETURN_NO_NOT_EXIST = "500043";//退货单不存在
    public static final String ORDER_RETURN_APPROVED = "500044";//退货单已审核
    public static final String ORDER_REFUND_APPROVED = "500045";//退款单已审核
    public static final String ORDER_RETURN_STATUS_ERROR = "500046";//售后记录状态错误
    public static final String ORDER_RETURN_SUPPLIER_ERROR = "500047";//售后记录商家错误
    public static final String ORDER_RETURN_TYPE_ERROR = "500048";//售后类型错误
    public static final String REQUEST_PROCESSING = "500049";//请求处理中
    public static final String GENERATE_ORDER_NO_ERROR = "500050";//生成订单号错误
    public static final String CREATE_ORDER_ERROR = "500051";//创建订单错误
    public static final String STOCK_IS_NOT_ENOUGH = "500052";//库存不足

    public static final String PREPARATION_ORDER_ADD_ERROR = "500056";//添加预订单错误
    public static final String EXPRESS_INFO_IS_NOT_EXIST_ERROR = "500053";//快递信息不存在
    public static final String REFUND_APPLY_ERROR = "500054";//退款金额申请错误
    public static final String CART_IS_NOT_EXIST = "500055";//购物车不存在
    public static final String ORDER_COMMENT_CAN_NOT_MODIFY = "500056"; // 订单评论不能修改

    public static final String NOT_ENOUGH_POINTS = "500057"; // 积分不足

    public static final String GOODS_DELETE_STATUS_STOTCK_ERROR = "500058"; //商品已删除、已下架或库存不足

    /*-----------------------------------------------------商品--------------------------------------------------**/
    public static final String GOODONETYPE_NOT_EXIST = "6000000";
    public static final String GOODTWOTYPE_NOT_EXIST = "6000001";
    public static final String GOODBRAND_NOT_EXIST = "6000002";
    public static final String GOODSUPPLIER_NOT_EXIST = "6000003";
    public static final String GOODSTORE_EXIST = "6000004";
    public static final String GOODINFO_EXIST = "6000005";
    public static final String GOODINFO_NOT_EXIST = "6000006";
    public static final String TRAN_PRICE_ERROR = "6000007";
    public static final String TRAN_COMPANY_ERROR = "6000008";
    public static final String GOODINFO_COUNT = "6000009";
    public static final String GOODONETYPE_NAME_ERROR = "6000010";
    public static final String GOODSTYPE_UPDATE_ERROR = "6000011";
    public static final String GOODINFO_BRAND_COUNT = "6000012";
    public static final String GOODBRAND_NAME_ERROR = "6000013";
    public static final String GOODSTYPE_NAME_ERROR = "6000014";
    public static final String DOODS_TYPE_NOT = "6000015";
    public static final String GOODS_ALL_DATA_ERROE = "6000016";
    public static final String JSON_SPECE_OPEN = "6000017";
    public static final String SUPPLIER_NOT_EXIST = "6000018";
    public static final String MERCHANT_SUPPLIER_EXCEPTION = "6000019";
    public static final String STOCK_MIN_DATA_ERR = "6000020";
    public static final String GOOD_BASIC_INFO_UNCOMP_FOR_PUBLISH = "6000021";
    public static final String GOOD_DETAIL_INFO_UNCOMP_FOR_PUBLISH = "6000022";
    public static final String EXPRESS_INFO_ERROR = "6000023";//商品快递信息有误
    public static final String ADDRESS_INFO_ERROR = "6000024";//商品快递信息有误
    public static final String GOODSSKUCODE_TOO_LONG = "6000025";//商品编码过长
    public static final String GOODINFO_NOT_ADMIN = "6000026";//添加自营商品但权限不是管理员
    public static final String GOODS_TOP_NUM_LIMIT = "6000027";//商品置顶数量已满
    public static final String GOODS_SORT_NO_ERROR = "6000028";//商品排序区间有误
    public static final String GOODS_AUDIT_ERROR = "6000029";//审核状态有误
    public static final String GOODS_SUPPLIER_ERROR = "6000030";//审核状态有误
    public static final String GOODINFO_NOT_ADMIN_BRAND = "6000031";//审核状态有误
    public static final String GOODINFO_NOT_SUPPLIER_ERROR = "6000032";//审核状态有误

    /*------------------------------------------------审核相关-------------------------------------------------------**/
    public static final String PAYMENT_DAYS_REPETITION = "800000";
    public static final String ID_ERROR_NULL = "800001";        //请求ID不能为空
    public static final String ID_ERROR_TYPE = "800002";       //请求ID格式错误，只能为数字类型
    public static final String ID_DATABASE_NOT = "800003";      //该ID在数据库里不存在或者已删除
    public static final String PARAM_ERROR_NULL = "800004";     //请求参数不能为空
    public static final String MERCHANT_NAME_ERROR = "800005";  //商家名称不能为空
    public static final String MERCHANT_TYPE_NULL_ERROR = "800006";   //商家类型不能为空
    public static final String MERCHANT_TYPE_ERROR = "800007";  //该商家类型在数据库里不存在
    public static final String MERCHANT_ID_ERROR = "800008";   //商家ID号码生成失败
    public static final String AUDIT_ID_NULL_ERROR = "800009"; //审核ID不可为空
    public static final String AUDIT_TYPE_NULL_ERROR = "800010"; //审核类型不能为空
    public static final String AUDIT_FEEDBACKMESSAGE_NULL = "800011";  //如果审核不通过,反馈详情不可为空
    public static final String AUDIT_TYPE_ERROR_TYPE = "800012"; //审核类型格式错误，只能为数字
    public static final String SYSUSER_NULL_ERROR = "800013";    //当前用户信息获取失败，请重新登录
    public static final String AUDIT_TYPE_ERROR = "800014";    //审核类型不存在
    public static final String MERCHANT_USER_NOT_EXIST = "800015"; //新增商家时获取不到用户信息[账号可能被停用或删除]
    public static final String AUDIT_USER_NOT_EXIST = "800016"; // 审核时获取不到用户信息[账号可能被停用或删除]
    public static final String LOGGABLE_NOT_NULL = "800017";  //操作日志获取自定义注解失败
    public static final String OPERATIONLOG_USER_NOT_EXIST = "800018"; //写入日志获取不到用户信息[账号可能被停用或删除]
    public static final String AUDIT_ADD_NULL_ERROR = "800019"; //写入审核参数(审核记录,审核类型,审核内容,申请人,申请时间)不可为空
    public static final String AUDIT_STATE_ERROR = "800020";// 审核状态只能是未审核
    public static final String AUDITS_NULL_ERROR = "800025"; //获取审核详情时失败
    public static final String CODE_ROLEID_NULL_ERROR = "800026"; //商家账号和角色不可为空
    public static final String AUDIT_MERCHANT_NULL = "800027"; //审核商家时获取审核详情失败
    public static final String AUDIT_MERCHANT_ERROR_NULL = "800028"; //审核商家时获取商家详情失败
    public static final String ADDRESS_ERROR_NULL = "800029"; //地址传入错误
    public static final String PROVINCE_ERROR_NULL = "800030"; //省信息不存在，请重新选择
    public static final String CITY_ERROR_NULL = "800031"; // 市信息不存在，请重新选择
    public static final String REGION_ERROR_NULL = "800032";  //区或县信息不存在，请重新选择
    public static final String MERCHANT_MERCDETAILS_NULL = "800033"; //获取不到商家详情
    public static final String MERCHANT_COUNT_NULL = "800034"; //商家详情得数据沉淀获取失败
    public static final String MERCHANT_SALE_NULL = "800035"; //商家详情得任务信息获取失败
    public static final String MERCHANT_AUDIT_NULL = "800036"; //商家详情得审核信息获取失败
    public static final String SUBINFOSOURCE_NULL_ERROR = "800037"; //申请来源不能为空
    public static final String SUBINFOSOURCE_ERROR = "800038"; //申请来源不存在，请重新选择
    public static final String MERCHANT_CODE_REPEAT_ERROR = "800039"; //商家用户账号已存在
    public static final String UPDATE_MERCHANT_ERROR = "800040"; //修改商家时不可传账号和角色
    public static final String MERCHANT_MOBILE_REPEAT_ERROR = "800041"; //商家电话号码已存在
    public static final String MERCHANT_LINKMAN_REPEAT_ERROR = "800042"; //商家联系人已存在
    public static final String AUDIT_MERCHANT_ID_NULL = "800043"; //商家写入审核记录时商家ID必填
    public static final String AUDIT_TASK_ID_NULL = "800044"; // 任务写入审核记录时任务ID必填
    public static final String AUDIT_SALEMISSION_ID_NULL = "800045"; //业务员任务写入审核记录时业务员任务ID必填
    public static final String ARTICLE_TYPE_NULL = "800046"; //文章类型不存在，请重新选择
    public static final String MERCHANT_CODE_NULL_ERROR = "800047";//新增商家时，商家账号不可为空
    public static final String ROLE_ID_NULL_ERROR = "800048"; //新增商家时，角色不可为空
    public static final String MERCHANT_IMG_NULL = "800049"; //商家详情得图片信息获取失败
    public static final String MERCHANT_IMG_ERROR = "800050"; //图片格式转化失败
    public static final String MERCHANT_AUDIT_ERROR = "800051"; //审核商家出错
    public static final String MERCHANT_IDS_ERROR = "800052"; //图片唯一标识获取失败
    public static final String MERCHANT_PHONE_ERROR = "800053"; //商家联系电话已存在
    public static final String AUDIT_MERCHANT_ID = "800054"; //商家ID写入审核列表中重复
    public static final String AUDIT_TASK_ID = "800055"; //任务ID写入审核列表中重复
    public static final String AUDIT_SALEMISSION_ID = "800056"; //任务员任务ID写入审核列表中重复
    public static final String AUDIT_TYPE_NOT_EXIST = "800057"; //审核通过后不可继续审核
    public static final String BATCH_AUDIT_TYPE_NOT_EXIST = "800058"; //批量审核中含有已通过审核得数据，批量审核失败
    public static final String APP_SALAEMAN_ERROR = "800059"; //获取业务员信息失败
    public static final String APP_SALASMAN_PARAM_ERROR_NULL = "800060"; //业务员提交任务审核参数为空
    public static final String APP_SALASMAN_MISSION_NULL = "800061"; //获取业务员任务信息失败
    public static final String SALE_MERCHANT_ERROR_NULL = "800062"; //业务员领取任务，获取商家信息时失败
    public static final String AUDIT_SALEMISSION_DETAILS_ID_NULL = "800063"; //获取业务员任务详情ID不可为空
    public static final String AUDIT_SALEMISSION_IMG = "800064"; //审核业务员任务时获取任务图片失败
    public static final String AUDIT_SALEMISSION_SALEMAN = "800065"; //审核业务员任务时，业务员详情获取失败
    public static final String AUDIT_SALEMISSION_SALEMANID = "800066"; //审核业务员任务时，业务员ID获取失败
    public static final String AUDIT_APPLY_RECORD_ID_NULL = "800067"; //后台加款写入审核记录时加款ID必填
    public static final String APPLY_RECORD_AUDIT_DETAILS = "800068"; //审核后台加款时获取审核详情失败
    public static final String INVOICE_AUDIT_DETAILS = "800068"; //审核后台商家发票时获取审核详情失败
    public static final String AUDIT_APPLY_DETAILS_NULL = "800069";  //审核后台加款时获取后台加款详情失败
    public static final String MERCHANT_CODE_ERROR = "800070"; //注册商家账号失败
    public static final String TASK_TYPE_NULL = "800071"; //任务类型不存在
    public static final String AUDIT_DETAILS_NULL = "800072"; //审核详情获取失败
    public static final String MERCHANT_NAME_REPEAT_ERROR = "800073"; //商家名称不可重复
    public static final String AUDIT_SALE_MISSION = "800074"; //业务员所做得任务只可审核一次
    public static final String AUDIT_TASK_DETAILS = "800075"; //审核业务员任务时，任务详情获取失败
    public static final String AUDIT_TASK_ERROR = "800076"; //审核任务为通过时，该任务不存在或者已删除
    public static final String MERCHANT_BALANCE_ERROR = "800077"; //商家余额只能从后台加款处增加
    public static final String IDARRAY_AUDIT_NULL = "800078"; //批量审核时，获取不到审核ID
    public static final String SALEMAN_TASK_IMG_NULL = "800079";//业务员做任务提交审核时获取不到图片
    public static final String MERCHANT_IMG_NULL_ERROR = "800080"; //添加商家时商家图片不可为空
    public static final String AUDIT_APPLY_RECORD_DETAILS_ID_NULL = "800081"; //审核后台加款时，加款ID不可为空
    public static final String ARTICLE_TITLE_ERROR = "800082"; //文章名称不可重复
    public static final String AUDIT_APPLY_RECORD_ID = "800083"; //后台加款ID写入审核列表中重复
    public static final String AUDIT_SALEMISSION_DETAILS = "800084"; //获取业务员任务详情失败
    public static final String AUDIT_MERCHANT_DETAILS_NULL = "800085"; //审核后台加款时获取商家详情失败
    public static final String MERCHANT_REGISTER_NULL = "800086"; //注册商家账号失败
    public static final String MERCHANT_REGISTER_ERROR = "800087"; //商家注册账号失败
    public static final String APP_TASK_ERROR = "800088"; //任务不存在
    public static final String AUDIT_APPLY_RECORD_ERROR = "800089"; //审核时加款详情获取失败
    public static final String MERCHANT_LOGIN_ERROR = "800090";//非商家账户无法登录
    public static final String SYSUSER_LOGIN_ERROR = "800091";//非运营账户无法登录
    public static final String AUDIT_MERCHANT_ERROR_USER_NULL = "800092"; //审核商家时获取商家用户ID详情失败
    public static final String MERCHANT_ERROR_NULL = "800093"; //商家账号不存在
    public static final String SYSUSERS_ERROR_NULL = "800094"; //商家用户ID不存在
    public static final String MERCHANT_ACCOUNT_ERROR = "800095";//商家余额更新失败
    public static final String MERCHANT_INVOICE_NULL = "800096";//商家发票信息获取失败
    public static final String AUDIT_APPLY_RECORD_NULL = "800097"; //审核时提款详情获取失败
    public static final String INVOICE_PARAM_NULL_ERROR = "810001"; //审核参数不可以为空
    public static final String INVOICE_COMPANY_NAME_ERROR = "810002";//公司（个人）发票抬头不可以为空
    public static final String INVOICE_DUTY_PARAGRAPH_NULL = "810003";//税号不可以为空
    public static final String INVOICE_UNIA_ADDRESS_NULL = "810004";//发票地址不可以为空
    public static final String INVOICE_WORK_PHONE_NULL = "810005";//单位电话不可以为空
    public static final String INVOICE_DEPOISTBANK_NULL = "810006";//开户银行不可以为空
    public static final String INVOICE_BANK_ACCOUNT_NULL = "810007";//银行账户不可以为空
    public static final String I_SUPPLIER_EXIST_ERROR = "810008";//已有商品存在该商家,禁止禁用！
    public static final String SUPPLIER_TAXPAYERNUMBER_ERROR = "810009";//纳税人号码只能输入中文，数字，字母，以及标点符号，长度50位！
    public static final String INVOICE_DUTY_PARAGRAPH_ERROR = "820003";//税号格式错误
    public static final String INVOICE_WORK_PHONE_ERROR = "820005";//单位电话格式错误
    public static final String INVOICE_DEPOISTBANK_ERROR = "820006";//开户银行格式错误
    public static final String INVOICE_BANK_ACCOUNT_ERROR = "820007";//银行账户格式错误
    public static final String ADDRESS_NOT_EXIST = "820008";//地址不存在
    public static final String OPERATION_WITHOUT_PERMISSION = "820009";//没有操作权限
    /*---------------------------------------------------答题---------------------------------------------------**/
    public static final String REDATE_ERROR = "0000064";//数据重复
    public static final String ERROR_MOVE = "0000065";//错误
    public static final String PARAM_TYPE_NULL = "0000066";//错误
    public static final String ANSWERS_ERROE = "0000067";//回答错误
    public static final String TOPIC_TYPE_NULL = "0000068";//题类型错误
    public static final String PHONE_ERROR_FORMAT = "0000069";//手机号码格式错误
    public static final String RE_ADDRESS_ERROR = "0000070";//地址重复
    /*-----------------------------------------------商品相关--------------------------------------------------------**/
    public static final String EXPRESS_SERIAL_ERROR = "0000071";//当前传入快递类型暂未开通
    public static final String PRODUCT_ORDER_NULL = "0000072";//订单不存在
    public static final String OPERATE_ERROR = "0000073";//操作失败
    public static final String SYSTEM_BUSY = "0000074";//操作失败
    public static final String STOCK_MIN_ERROR = "0000075";//库存量不足或商品不存在
    public static final String STORE_PRICE_CHANGE = "0000076";//商品价格发生变化。请重新操作
    public static final String EXCHANGE_MONEY_ERROR = "0000077";//兑换商品超出限量
    public static final String NOT_SUPPORT_PAYTYPE = "0000078";//当前暂不支持微信，支付宝支付
    public static final String CLOSE_ORDERTYPE_ERROR = "0000079";//当前订单不可取消。如需取消请联系客服进行操作
    public static final String ORDERNOT_YOURSELF_ERROR = "0000080";//当前订单不为你的。不可取消
    public static final String GOODS_SPECE_NULL = "0000081";//商品不存在【或规格更改】
    public static final String REJECT_SPITE_REQUEST = "0000082";//拒绝恶意的访问
    public static final String HAVA_ORDER_USE = "0000083";//有订单使用当前快递。无法删除
    public static final String MAX_GOODS_CHANGE = "0000084";//商品兑换上限【可能当前数量超过限制】
    public static final String SPECE_DATE_ERROR = "0000085";//规格相关数据错误
    public static final String FAKE_GOOD_NOSUPPORT = "0000086";//虚拟商品暂不支持
    public static final String EXPRESS_SYS_ERROR = "0000087";//快递系统异常
    public static final String DEFAULT_ADDRESS_NULL = "0000088";//当前暂无默认地址
    public static final String MAX_ADDRESS_ERROR = "0000089";//添加收货地址上限【请删除或修改已保存地址】
    public static final String BACK_DATA_ERROR = "0000090";//后台数据异常【或商品正在维护】
    public static final String BUYADDRESS_LENGHT_ERROR = "0000091";//地址详细传入错误【0-30位汉字字符数字+,(注意大小写)】
    public static final String EXPRESS_ORDERNO_NULL = "0000092";//订单未发货
    public static final String PHONE_CODE_ERROR = "0000093";//短信验证码已过期
    public static final String PHONE_NO_CODE_ERROR = "0000094";//短信验证码不正确
    public static final String PHONE_CODE_SEND_LIMMIT = "0000095";//验证码发送频繁,请60秒后重试
    public static final String TASK_AWARDDATA_ERROR = "0000096";//任务携带赏金或积分错误
    public static final String WXGET_RELATED_ERROR = "0000097";//微信签名获取相关参数
    public static final String WXORDER_QUERY_ERROR = "0000098";//微信订单查询失败，或【订单已支付或关闭】
    public static final String ORDER_NOT_BACK = "0000099";//订单不可退货退款
    public static final String SALE_NOT_EXIST_WEIXIN = "0000100";//该业务员不在微信平台,无法提现
    public static final String WXORDER_TRANSFER_ERROR = "0000101";//微信支付异常,请联系专业人员!
    public static final String WECHAT_SALE_NOT_EXIST = "0000102";//未查询到微信登录人
    public static final String ADD_TASK_SALEMAN_ERROR = "0000103";//任务领取失败
    public static final String ORDER_CLOSE_ERROR = "0000104";//当前订单不可取消
    public static final String OPERATE_TIMEOUT_ERROR = "0000105";//操作超时,请重试
    public static final String OPERATE_OFTEN_ERROR = "0000106";//操作太频繁,请重试
    public static final String STOCK_NONE_ERROR = "0000107";//商品库存量不足
    public static final String DELETE_CONSULT_ERROR = "0000108";//有咨询未处理，无法删除
    public static final String CONSULT_REPEAT_ERROR = "0000109";//信息已提交，请24小时后再试
    public static final String HAS_CHECKED = "0000110";//此订单已核销
    public static final String ERROR_PICKUP_SITE = "0000111";//此订单不属于该自提点
    public static final String CAN_NOT_PICKUP_STATUS = "0000112";//订单状态不可提货
    public static final String PICKUP_SITE_NULL_ERROR = "0000113";//自提点不存在或已删除
    public static final String PICKUP_SITE_FORBIDDEN_STATUS = "0000114";//自提点功能已禁用，如有疑问请联系客服
    public static final String PHONE_JSCODE_ERROR = "0000115";//自提点功能已禁用，如有疑问请联系客服
    public static final String GOODS_NOT_EXIST = "0000115";//商品不存在

    public static final String DELIVERY_ERROR = "0000116";//发货异常
    public static final String ORDER_AUTHORIZATION_ERROR = "0000117";//发货异常
    //    微信相关-----------------------------------------------------------------------------------------------
    public static final String WX_OPENID_ERROR = "7000001";
    public static final String WX_LOGIN_OTHER_PHONE_ERROR = "7000002"; // 该微信已绑定其他账号
    public static final String WX_LOGIN_OTHER_WX_ERROR = "7000003";

    /*---------------------------------------------------服务站相关---------------------------------------------------**/

    public static final String REPEAT_SERVICE_SITE_NUMBER = "900001";
    public static final String STOCK_OUT_MORE_THAN_STOCK = "900002";

    private ResponseCode() {
    }

}
